import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthButton from "@/components/AuthButton";
import { auth } from "@/auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode;}>) {
    const session = await auth();
    const isExec = session?.user?.role === "EXEC";
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header className="flex items-center justify-between border-b border-gray-200 bg-white px-8 py-3">
          <nav className="flex items-center gap-4 text-sm">
            <span className="font-semibold text-gray-900">SmartHQ Fleet</span>
            <a href="/" className="text-gray-600 hover:text-gray-900">Ops</a>
            <a href="/assistant" className="text-gray-600 hover:text-gray-900">Assistant</a>
            {isExec && <a href="/business" className="text-gray-600 hover:text-gray-900">Business</a>}
          </nav>
          <AuthButton />
        </header>
        {children}
      </body>
    </html>
  );
}
